### ISSUE TITLE
Bug majeur logiciel

### ISSUE THREAD

**Issue by Sn0wAlice** [daprofiler/DaProfiler#12]
```
Traceback (most recent call last):
  File "/Users/alice/Documents/.../profiler.py", line 380, in <module>
    data = instagram_search.get_extra_data(username)
  File "/Users/alice/Documents/.../modules/instagram_search.py", line 404, in get_extra_data
    status = data['user']['status']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Sn0wAlice** [comment]
patched
