### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by FloMtrn** [daprofiler/DaProfiler#34]
Traceback (most recent call last):
  File "/home/florian/DaProfiler/profiler.py", line 165, in <module>
    wattpad_results = wattpad_search.wattpad_module(pren,name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/DaProfiler/modules/social_medias/wattpad_search.py", line 9, in wattpad_module
    driver = webdriver.Firefox(options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/selenium/webdriver/firefox/webdriver.py", line 196, in __init__
    super().__init__(command_executor=executor, options=options, keep_alive=True)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1

**Comment by FloMtrn** [comment]
Please help me to fix this, I don't understand.

**Comment by FloMtrn** [comment]
EDIT: Fixed by doing sudo chmod -R 777 /home/pcname/Daprofiler/profiler.py
